// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: ordencliente.proto

package ordencliente

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OrdenCliente struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Producto    string `protobuf:"bytes,2,opt,name=producto,proto3" json:"producto,omitempty"`
	Valor       int32  `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Tienda      string `protobuf:"bytes,4,opt,name=tienda,proto3" json:"tienda,omitempty"`
	Destino     string `protobuf:"bytes,5,opt,name=destino,proto3" json:"destino,omitempty"`
	Prioritario bool   `protobuf:"varint,6,opt,name=prioritario,proto3" json:"prioritario,omitempty"`
}

func (x *OrdenCliente) Reset() {
	*x = OrdenCliente{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ordencliente_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrdenCliente) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdenCliente) ProtoMessage() {}

func (x *OrdenCliente) ProtoReflect() protoreflect.Message {
	mi := &file_ordencliente_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdenCliente.ProtoReflect.Descriptor instead.
func (*OrdenCliente) Descriptor() ([]byte, []int) {
	return file_ordencliente_proto_rawDescGZIP(), []int{0}
}

func (x *OrdenCliente) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrdenCliente) GetProducto() string {
	if x != nil {
		return x.Producto
	}
	return ""
}

func (x *OrdenCliente) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *OrdenCliente) GetTienda() string {
	if x != nil {
		return x.Tienda
	}
	return ""
}

func (x *OrdenCliente) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *OrdenCliente) GetPrioritario() bool {
	if x != nil {
		return x.Prioritario
	}
	return false
}

var File_ordencliente_proto protoreflect.FileDescriptor

var file_ordencliente_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6f, 0x72, 0x64, 0x65, 0x6e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6f, 0x72, 0x64, 0x65, 0x6e, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x65, 0x22, 0xa4, 0x01, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x6e, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x65, 0x6e, 0x64, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x65, 0x6e, 0x64, 0x61, 0x12, 0x18, 0x0a,
	0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x6f, 0x72,
	0x69, 0x74, 0x61, 0x72, 0x69, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x70, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x61, 0x72, 0x69, 0x6f, 0x32, 0x5f, 0x0a, 0x13, 0x4f, 0x72, 0x64,
	0x65, 0x6e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x48, 0x0a, 0x0c, 0x52, 0x65, 0x64, 0x65, 0x63, 0x69, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x6e,
	0x12, 0x1a, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x6e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x6e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x1a, 0x1a, 0x2e, 0x6f,
	0x72, 0x64, 0x65, 0x6e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x6e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_ordencliente_proto_rawDescOnce sync.Once
	file_ordencliente_proto_rawDescData = file_ordencliente_proto_rawDesc
)

func file_ordencliente_proto_rawDescGZIP() []byte {
	file_ordencliente_proto_rawDescOnce.Do(func() {
		file_ordencliente_proto_rawDescData = protoimpl.X.CompressGZIP(file_ordencliente_proto_rawDescData)
	})
	return file_ordencliente_proto_rawDescData
}

var file_ordencliente_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ordencliente_proto_goTypes = []interface{}{
	(*OrdenCliente)(nil), // 0: ordencliente.OrdenCliente
}
var file_ordencliente_proto_depIdxs = []int32{
	0, // 0: ordencliente.OrdenClienteService.RedecirOrden:input_type -> ordencliente.OrdenCliente
	0, // 1: ordencliente.OrdenClienteService.RedecirOrden:output_type -> ordencliente.OrdenCliente
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ordencliente_proto_init() }
func file_ordencliente_proto_init() {
	if File_ordencliente_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ordencliente_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrdenCliente); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ordencliente_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ordencliente_proto_goTypes,
		DependencyIndexes: file_ordencliente_proto_depIdxs,
		MessageInfos:      file_ordencliente_proto_msgTypes,
	}.Build()
	File_ordencliente_proto = out.File
	file_ordencliente_proto_rawDesc = nil
	file_ordencliente_proto_goTypes = nil
	file_ordencliente_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrdenClienteServiceClient is the client API for OrdenClienteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrdenClienteServiceClient interface {
	RedecirOrden(ctx context.Context, in *OrdenCliente, opts ...grpc.CallOption) (*OrdenCliente, error)
}

type ordenClienteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrdenClienteServiceClient(cc grpc.ClientConnInterface) OrdenClienteServiceClient {
	return &ordenClienteServiceClient{cc}
}

func (c *ordenClienteServiceClient) RedecirOrden(ctx context.Context, in *OrdenCliente, opts ...grpc.CallOption) (*OrdenCliente, error) {
	out := new(OrdenCliente)
	err := c.cc.Invoke(ctx, "/ordencliente.OrdenClienteService/RedecirOrden", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrdenClienteServiceServer is the server API for OrdenClienteService service.
type OrdenClienteServiceServer interface {
	RedecirOrden(context.Context, *OrdenCliente) (*OrdenCliente, error)
}

// UnimplementedOrdenClienteServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrdenClienteServiceServer struct {
}

func (*UnimplementedOrdenClienteServiceServer) RedecirOrden(context.Context, *OrdenCliente) (*OrdenCliente, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedecirOrden not implemented")
}

func RegisterOrdenClienteServiceServer(s *grpc.Server, srv OrdenClienteServiceServer) {
	s.RegisterService(&_OrdenClienteService_serviceDesc, srv)
}

func _OrdenClienteService_RedecirOrden_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrdenCliente)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdenClienteServiceServer).RedecirOrden(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ordencliente.OrdenClienteService/RedecirOrden",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdenClienteServiceServer).RedecirOrden(ctx, req.(*OrdenCliente))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrdenClienteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ordencliente.OrdenClienteService",
	HandlerType: (*OrdenClienteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RedecirOrden",
			Handler:    _OrdenClienteService_RedecirOrden_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ordencliente.proto",
}
